name: Main-branch (Production) deploy actions
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v1

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Create .env
        shell: bash
        run: |
          touch .env
          echo REACT_APP_BASE_URL=${{secrets.REACT_APP_BASE_URL_PRODUCTION}} >> .env
          echo REACT_APP_APP_ID=${{secrets.REACT_APP_APP_ID_PRODUCTION}} >> .env
          echo REACT_APP_MINI_PRESET=${{secrets.REACT_APP_MINI_PRESET_PRODUCTION}} >> .env
          echo REACT_APP_MINI_INSTALLATION_URL=${{secrets.REACT_APP_MINI_INSTALLATION_URL_PRODUCTION}} >> .env
          echo REACT_APP_FIREBASE_API_KEY=${{secrets.REACT_APP_FIREBASE_API_KEY_PRODUCTION}} >> .env
          echo REACT_APP_FIREBASE_AUTH_DOMAIN=${{secrets.REACT_APP_FIREBASE_AUTH_DOMAIN_PRODUCTION}} >> .env
          echo REACT_APP_FIREBASE_PROJECT_ID=${{secrets.REACT_APP_FIREBASE_PROJECT_ID_PRODUCTION}} >> .env
          echo REACT_APP_FIREBASE_STORAGE_BUCKET=${{secrets.REACT_APP_FIREBASE_STORAGE_BUCKET_PRODUCTION}} >> .env
          echo REACT_APP_FIREBASE_MESSAGING_SENDER_ID=${{secrets.REACT_APP_FIREBASE_MESSAGING_SENDER_ID_PRODUCTION}} >> .env
          echo REACT_APP_FIREBASE_APP_ID=${{secrets.REACT_APP_FIREBASE_APP_ID_PRODUCTION}} >> .env
          echo REACT_APP_FIREBASE_MEASUREMENT_ID=${{secrets.REACT_APP_FIREBASE_MEASUREMENT_ID_PRODUCTION}} >> .env

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          AWS_REGION: 'ap-northeast-2'
          AWS_S3_BUCKET: ${{secrets.AWS_S3_BUCKET_PRODUCTION}}
          SOURCE_DIR: 'build'
